### ISSUE TITLE
"The two lines are parallel!" Error

### ISSUE THREAD

**Issue by murasu** [visioncortex/visioncortex#9]
I'm trying to trace an Image I already have in memory. I'm able to create a BinaryImage with the data and call the core libraries to do the tracing. It works in most cases, except that it panics with the above error for some images. I see some notes in the find_intersection function in utils.rs - but I don't know what to make out of it. 

I'm not familiar with Rust. I just started learning in order to use this wonderful library. I'm doing most of the work in C++ and calling rust just to trace the bitmap. My bitmaps are just one bit. Easy to create BinaryImages.

I can get the first pass (staircase) trace in C++, but I don't know where to look for the entry point in vision cortex  with that data. I'm not sure it that will make a difference.  Appreciate any pointers you can provide.  

Thank you!

**Comment by tyt2y3** [comment]
Umm that's strange. Can you dump your binary image into a reproducible example? There are probably some edge cases we didn't handle.

**Comment by murasu** [comment]
Thank you! I've placed the code and the images here: 

https://www.dropbox.com/s/xw5u17k9il2hkp3/VCTracingBug.zip?dl=0

There are two experiments and I've documented them in the code.

**Comment by tyt2y3** [comment]
For posterity, the offending image is this:

![image](https://github.com/visioncortex/visioncortex/assets/1782664/76c4eb48-ea55-4d97-9bc8-2625451a9f76)

Calling:

```rust
cluster.to_compound_path(PathSimplifyMode::Spline, 60.0, 4.0, 10, 45.0);
```

**Comment by tyt2y3** [comment]
I did manage to make it not crash.
However, I would suggest using a smaller `length_threshold`:

```rust
cluster.to_compound_path(PathSimplifyMode::Spline, 60.0, 1.0, 10, 45.0);
```

which would give

![image](https://github.com/visioncortex/visioncortex/assets/1782664/986d1e1f-2a86-4bc7-9f33-0592d3ac8c7a)

**Comment by tyt2y3** [comment]
I pushed a patch to master, so if you change your Cargo.toml to the following:

```rust
visioncortex = { version = "0.8.0", git = "https://github.com/visioncortex/visioncortex" }
```

it should have avoided the crash.

The fix is pretty dead dumb, but it's an edge case, so I don't expect to have any overall impact. If you can confirm the fix is good, I could probably make a source release `0.8.1`.

Btw, my personal GitHub Sponsor profile is up. So if you feel generous you can buy me a beer. Cheers.

**Comment by murasu** [comment]
Thank you! I added the git url and that fixed the crash. Also stepped the length_treshold down to 1 and see improvements in the output.  However, it's still not as good as the svg output from the command line version of VTracer, though.  I am not sure if it is the way I generate EPS from the control points I'm getting back. I'll check this further and feedback.

In the image below, the one on the left is what I get with my code and the one on the right is from VTracer. 

<img width="839" alt="the_glyph_from_data_eps____100____CMYK_Preview_" src="https://github.com/visioncortex/visioncortex/assets/22926756/a201ec3d-74c2-4967-9469-9bff49fd8e52">

**Comment by murasu** [comment]
> I pushed a patch to master, so if you change your Cargo.toml to the following:
> 
> ```rust
> visioncortex = { version = "0.8.0", git = "https://github.com/visioncortex/visioncortex" }
> ```
> 
> it should have avoided the crash.
> 
> The fix is pretty dead dumb, but it's an edge case, so I don't expect to have any overall impact. If you can confirm the fix is good, I could probably make a source release `0.8.1`.
> 
> Btw, my personal GitHub Sponsor profile is up. So if you feel generous you can buy me a beer. Cheers.

I just bought you a beer for the quick work. Thank you! However, I have dropped this library in favour of https://gist.github.com/gumblex/047abdd163c3a3c96b64. Nevertheless, I will keep a lookout and come back here when I need to trace color images in the future. Keep up the great work!

**Comment by tyt2y3** [comment]
Thank you so much! No problem. Good luck to your project!
